import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { DEVELOPER, OWNER, SUPER_ADMIN } from '@/constants/roles.constant'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'Apps',
        translateKey: 'nav.apps.apps',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            // Dashboard
            {
                key: 'apps.dashboard',
                path: '/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.apps.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // Manajemen Proyek
            {
                key: 'apps.manajemenProyek',
                path: '/manajemen-proyek',
                title: 'Manajemen Proyek',
                translateKey: 'nav.apps.manajemenProyek',
                icon: 'manajemenProyek',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [
                    {
                        key: 'apps.proyek',
                        path: '/manajemen-proyek/proyek',
                        title: 'Proyek',
                        translateKey: 'nav.apps.manajemenProyek.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.timeline',
                        path: '/manajemen-proyek/timeline',
                        title: 'Timeline',
                        translateKey: 'nav.apps.manajemenProyek.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.tender',
                        path: '/manajemen-proyek/tender',
                        title: 'Tender',
                        translateKey: 'nav.apps.manajemenProyek.item3',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.adendum',
                        path: '/manajemen-proyek/adendum',
                        title: 'Adendum',
                        translateKey: 'nav.apps.manajemenProyek.item4',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN, OWNER, DEVELOPER],
                        subMenu: [],
                    },
                    {
                        key: 'apps.tagihanKlien',
                        path: '/manajemen-proyek/tagihan-klien',
                        title: 'Tagihan Klien',
                        translateKey: 'nav.apps.manajemenProyek.item5',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN, OWNER, DEVELOPER],
                        subMenu: [],
                    },
                    {
                        key: 'apps.tagihanProyek',
                        path: '/manajemen-proyek/tagihan-proyek',
                        title: 'Tagihan Proyek',
                        translateKey: 'nav.apps.manajemenProyek.item6',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN, OWNER, DEVELOPER],
                        subMenu: [],
                    },
                ],
            },
            // Master
            {
                key: 'apps.master',
                path: '/master',
                title: 'Master',
                translateKey: 'nav.apps.master.collapse',
                icon: 'master',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'apps.klien',
                        path: '/master/klien',
                        title: 'Klien List',
                        translateKey: 'nav.apps.master.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.berkas',
                        path: '/master/berkas',
                        title: 'Berkas Tagihan',
                        translateKey: 'nav.apps.master.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },

                    {
                        key: 'apps.subkontraktor',
                        path: '/master/subkontraktor',
                        title: 'Subkontraktor',
                        translateKey: 'nav.apps.master.item3',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.satuan',
                        path: '/master/satuan',
                        title: 'Satuan',
                        translateKey: 'nav.apps.master.item4',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.divisi',
                        path: '/master/divisi',
                        title: 'Divisi',
                        translateKey: 'nav.apps.master.item5',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // Peran Pengguna
            {
                key: 'apps.peranDanPengguna',
                path: '/peran-dan-pengguna',
                title: 'Peran & Pengguna',
                translateKey: 'nav.apps.peranDanPengguna.collapse',
                icon: 'peranDanPengguna',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN, DEVELOPER, OWNER],
                subMenu: [
                    {
                        key: 'apps.peran',
                        path: '/peran-dan-pengguna/peran',
                        title: 'Peran',
                        translateKey: 'nav.apps.peranDanPengguna.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'apps.pengguna',
                        path: '/peran-dan-pengguna/pengguna',
                        title: 'Pengguna',
                        translateKey: 'nav.apps.peranDanPengguna.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // Logs
            {
                key: 'apps.logs',
                path: '/logs',
                title: 'Logs',
                translateKey: 'nav.apps.logs',
                icon: 'logs',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, DEVELOPER],
                subMenu: [],
            },
        ],
    },
]

export default appsNavigationConfig
